<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEOdYEJW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEOdYEJW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEOdYEJW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEOdYEJW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEOdYEJW\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EOdYEJW',
    'container.build_id' => '4069ae21',
    'container.build_time' => 1563885315,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEOdYEJW');
