<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\Container60e2mNx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container60e2mNx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container60e2mNx.legacy');
=======
if (\class_exists(\ContainerUJX0FoB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUJX0FoB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUJX0FoB.legacy');
>>>>>>> ace7a1bc507efe4c598950ac4f13d82c2d39e852

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\Container60e2mNx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container60e2mNx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '60e2mNx',
    'container.build_id' => '6eb9297b',
    'container.build_time' => 1564103505,
], __DIR__.\DIRECTORY_SEPARATOR.'Container60e2mNx');
=======
    \class_alias(\ContainerUJX0FoB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUJX0FoB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UJX0FoB',
    'container.build_id' => '3ee24bef',
    'container.build_time' => 1564067140,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUJX0FoB');
>>>>>>> ace7a1bc507efe4c598950ac4f13d82c2d39e852
