<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container60e2mNx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container60e2mNx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container60e2mNx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container60e2mNx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container60e2mNx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '60e2mNx',
    'container.build_id' => '6eb9297b',
    'container.build_time' => 1564103505,
], __DIR__.\DIRECTORY_SEPARATOR.'Container60e2mNx');
